# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-08 02:33
from __future__ import unicode_literals

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hoteis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_hotel', models.CharField(max_length=200)),
                ('apresentacao_hotel', models.TextField()),
                ('foto_hotel', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='foto_hotel')),
            ],
        ),
        migrations.CreateModel(
            name='Palestrantes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('apresentacao', models.TextField()),
                ('foto', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='foto')),
            ],
        ),
        migrations.CreateModel(
            name='Patrocinio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_patrocinio', models.CharField(max_length=200)),
                ('apresentacao_patrocinio', models.TextField()),
                ('foto_patrocinio', cloudinary.models.CloudinaryField(max_length=255, verbose_name='foto_patrocinio')),
            ],
        ),
    ]
