# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-09 03:06
from __future__ import unicode_literals

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comochegar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_lugar', models.CharField(max_length=200)),
                ('apresentacao_lugar', models.TextField()),
                ('foto_lugar', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='foto')),
            ],
        ),
        migrations.CreateModel(
            name='Minicursos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_minicurso', models.CharField(max_length=200)),
                ('apresentacao_minicurso', models.TextField()),
                ('foto_minicurso', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='foto_palestra')),
            ],
        ),
        migrations.CreateModel(
            name='Palestras',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_palestra', models.CharField(max_length=200)),
                ('apresentacao_palestra', models.TextField()),
                ('foto_palestra', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='foto_palestra')),
            ],
        ),
        migrations.CreateModel(
            name='Restaurantes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_restaurante', models.CharField(max_length=200)),
                ('apresentacao_restaurante', models.TextField()),
                ('foto_restaurante', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='foto_restaurante')),
            ],
        ),
        migrations.DeleteModel(
            name='Hoteis',
        ),
    ]
