# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-10 01:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20170309_0006'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Comochegar',
            new_name='Hoteis',
        ),
        migrations.RenameField(
            model_name='hoteis',
            old_name='apresentacao_lugar',
            new_name='apresentacao_hotel',
        ),
        migrations.RenameField(
            model_name='hoteis',
            old_name='foto_lugar',
            new_name='foto_hotel',
        ),
        migrations.RenameField(
            model_name='hoteis',
            old_name='nome_lugar',
            new_name='nome_hotel',
        ),
    ]
