# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-18 18:04
from __future__ import unicode_literals

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20170309_2247'),
    ]

    operations = [
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_evento', models.CharField(max_length=200)),
                ('apresentacao_evento', models.TextField()),
                ('foto_evento', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='foto')),
            ],
        ),
    ]
